[package]
name = "human_mortality_database"
version = "0.3.2"
edition = "2024"
authors = ["Christopher Gundler <christopher@gundler.de>"]
license = "MIT"
readme = "README.md"
description = "Query the Human Mortality Database"
repository = "https://github.com/Christopher22/human_mortality_database"
documentation = "https://christopher22.github.io/human_mortality_database/human_mortality_database/index.html"
categories = ["science"]
keywords = ["epidemiology", "demography", "mortality", "survival", "statistics"]

[lib]
crate-type = ["rlib", "cdylib"]

[features]
default = ["download"]
python = ["dep:pyo3"]
download = ["dep:reqwest", "dep:serde_urlencoded"]

[dependencies]
chrono = "0.4.44"
reqwest = { version = "0.13.2", optional = true, features = ["blocking", "cookies"] }
serde_urlencoded = { version = "0.7", optional = true }
pyo3 = { version = "0.23", optional = true, features = ["abi3-py39", "extension-module"] }
