[package]
name = "human_mortality_database"
version = "0.1.0"
edition = "2024"
authors = ["Christopher Gundler <christopher@gundler.de>"]
license = "MIT"
readme = "README.md"
description = "Query the Human Mortality Database"

[dependencies]
chrono = "0.4.44"
reqwest = { version = "0.13.2", features = ["blocking", "cookies"] }
serde_urlencoded = "0.7"
